### PR TITLE
Part 2

### PR DESCRIPTION
**Pull request by elizabethgeary**
Hi,

This is the progress I've made for the second section of the wiki :)

### CODE REVIEW

**Comment by garner-code** [comment]
Hi Lizzy

This is looking great so far :) I am not going to accept this pull request right now though. Please could you make a couple more additions and then re-request? 

First, can you please copy and paste your tables into your code, beneath where you have written the code that generates them? (be sure to comment them out).

Second, write comments on why you have chosen the tables you have, what you can learn from them in your analysis, and why you have chosen the functions you have. If you could keep your comments as detailed as possible for now, that would be great, as it teaches me what you know :)

Thanks, and great work coder girl! :)
Kel

**Comment by elizabethgeary** [comment]
Hey Kel,

I've just fixed it up and added a few new tables - let me know what you think :) 

I did want to create a table with the tract names and FA at the level of group and session but I couldn't quite figure out how to get there - Perhaps not essential for this bit? Also did I need RT data (or is it already in there and I'm not paying attention?)?

Thanks for your help :)
Coder girl Lizzy 

(Also, sorry that first message was so rude - I didn't know if it was going to some strange server that you wouldn't see and was like some nameless post in the big git world...)

**Comment by garner-code** [comment]
Hi Lizzy

Haha - no worries. I had not decoded any rudeness in your first message - just efficiency :)

This is a really good start - and I love the detail of the comments - thank youuuuuu! 

What we want to do at this step is get a feel of how many cases we have in the data for each tract. For example, how many subjects do we have in each group at pre and post (I know for sure that we don't have a drop out rate of 74). And it would also be useful to know how many participants are contributing an NA value for each tract at pre and at post (again, broken down by group would be great). - you also want to double check whether or not we have any duplicates in the data.

I would do something along the lines of:
summary <- data %>% group_by(session, group) %>% 
                                       summarise(N=length(some-variable))

Also, if you think the numbers look funny in anyway, given what you know about the number of subjects we had in the experiment, you can use this function in a similar way to above:
https://dplyr.tidyverse.org/reference/distinct.html

Here are some ideas on how to count the number of NAs you have for each tract:
https://sebastiansauer.github.io/sum-isna/

Knowing the mean at this point isn't so helpful. We'll be plotting that along with detailed info about the distribution real soon. Right now we just care about whether our data is all there/seems sensible in terms of the number of subjects etc/nothing crazy happened on the import.

Keep me posted on how you go CGL :)

**Comment by elizabethgeary** [comment]
Hi Kel - here is the updated first part - I'll get cracking on the second section now... Thank again for meeting with us today :)

Lizzy

**Comment by elizabethgeary** [comment]
- Sorry I've just realised by '#3" has accidentally referenced Georgias branch is that okay?

**Comment by garner-code** [comment]
Hey Lizzy

Looking good! Happy coding :)

Cheers
Kel

**Pull request merged**
